# Site settings
title: Medieval Archery Society
email: medievalarcherysociety@gmail.com
contact: medievalarcherysociety@gmail.com
description: >
    The Medieval Archery Society is a group of like minded people who primarily portray an English mercenary company (Free Company) in France circa 1350 based in Sydney, Australia.
keywords: >
    mas,medieval,archer,archery,society,re-enactment,reenactment,sydney,new,south,wales,australia,nsw
baseurl: ""
url: https://staging.medievalarchery.au

# Build settings
markdown: kramdown
timezone: Australia/Sydney

plugins:
  - jekyll-minifier
  - jekyll-gallery-generator
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    sass_dir: _sass

gallery:
  dir: gallery
  lightbox: true
  symlink: false
  title: "Gallery"
  title_prefix: "Gallery - "
  sort_field: "date_time"
  thumbnail_size:
    x: 200
    y: 200

galleries:
  winterfest:
    name: Winterfest
    best_image: winterfest-2017-05.jpg
    sort_reverse: true
  stives:
    name: St Ives
    best_image: stives-2018-22.jpg
    sort_reverse: true
  ironfest:
    name: Ironfest
    best_image: 2355497_orig.jpg
    sort_reverse: true
  opendays:
    name: Open Days
    best_image: opendays-2017-05.jpg
    sort_reverse: true
  general:
    name: General
    best_image: winterfest-2017-05.jpg
    sort_reverse: true
